# Generated by Django 3.1.1 on 2020-09-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_auto_20200925_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='symbol',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='ticker',
        ),
    ]
