# Generated by Django 3.1.1 on 2020-09-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0008_auto_20200927_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
